### PR TITLE
Remove clang-format and related code/tests

### LINKED ISSUE #882: Upgrade/pin or remove clang-format 14
Got an error message when running #881 that suggests that we need to do something about version of clang-format.

```
Run ./script/clang-format --check
Version of clang-format (clang-format) is 14, expected it to be one of 10, 11, 12
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by hnformentin**
**Issue**
Resolves #882

**Approach**
Remove test and code related to clang-format.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by lars-petter-hauge** [comment]
jenkins test this please

**Comment by berland** [comment]
Superseded by #891 ?

**Comment by xjules** [comment]
Closing this one as #891 is solving it.

**Pull request closed without merging**
