### PR TITLE
Fix issues on Windows related to PATH_MAX and mkdir

### PR DESCRIPTION
**Pull request by magnesj**
**Issue**
if Posix mkdir is detected, make sure that only one version of mkdir is used. Make sure PATH_MAX is defined
Add GitHub action for compile on Windows

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by dotfloat** [comment]
Looks a good start! Can you squash and then I'll merge it?

**Comment by sondreso** [comment]
Jenkins, test this please!

**Comment by magnesj** [comment]
Squashed and ready for merge

**Review by dotfloat — APPROVED** [review]

**Pull request merged**
