### PR TITLE
Resolve deprecation of imp module by removal,  fix 3.10 compatibility

### PR DESCRIPTION
**Pull request by berland**
Cleanup PR:

* Pin black for Py36 compatibility
* Remove 2.7 remnants in requirements.txt
* Resolve deprecation warning by removing unused code
* Resolve py3.10 distutils incompatibility, use assert allclose.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by dafeda** [comment]
Saw this one after I had already created this:

https://github.com/equinor/ecl/pull/853

My PR also fixes (I hope) failing tests in Python 3.10.

Do you want to merge mine into yours or the other way around?

**Comment by berland** [comment]
> Do you want to merge mine into yours or the other way around?
 
I'll merge the two!

**Comment by berland** [comment]
This PR is to be merged, not squashed

**Review by sondreso — APPROVED** [review]
LGTM!

**Pull request merged**
