### PR TITLE
Called with wrong arguments (don't explicitly pass self)

### PR DESCRIPTION
**Pull request by BjarneHerland**
The wrapped function `bool_vector_count_equal()` should not explicitly pass `self` since that is done implicitly. No idea why this works at all...

### CODE REVIEW

**Comment by berland** [comment]
This looks to actually resolve a bug uncaught in current testing:

```
173     def test_bool_vector(self):
174         b = BoolVector()
175         b.setDefault(True)
176
177         b[4] = False
178
179         self.assertEqual(list(b), [True, True, True, True, False])
180         self.assertEqual(b.count(True), 4)
181         self.assertEqual(b.count(False), 1)
```

Adding the lines 180 and 181, it will fail unless this patch is applied.

**Comment by BjarneHerland** [comment]
It's also worth noting that most of the wrapped methods in this class are not used, e.g. `_alloc`, `_alloc_copy`, `_assign`, `_equal`, `_sort_perm` etc.

**Comment by berland** [comment]
Can you rewrite commit message to state that this fixes a bug with count_equal in a BoolVector (and the other change)

**Review by berland — APPROVED** [review]
👍🏻

**Pull request closed without merging**
